# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6f067e4e66a9e27e77b7d92fcabed8f8704f2202525b06a57c02558fb630501e9e336eec43659913c214d44ecb1f9d8d50795269cbd813b088522f449451459

test:
  secret_key_base: f723861227c0edb6f414d05eeb0126a53001617e975312c089d43d4a0557a83635ccd4fccaaba7ed6ad5c1918e5d36e2149863d06fdba0e98502830b49ab613b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
